// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp, auth } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@2.108.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
function client(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List Peninsula Equine projects",
  description: "List Peninsula Equine's live build register \u2014 project name, location, build type, status and client-facing summary.",
  inputSchema: {
    status: z.string().optional().describe("Optional status filter (e.g. 'live', 'complete', 'planning')."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    let q = client(ctx).from("managed_projects").select("code,name,location,build_type,status,client_summary,last_update").eq("is_demo", false).order("sort_order", { ascending: true }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.108.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var list_services_default = defineTool2({
  name: "list_services",
  title: "List Peninsula Equine services",
  description: "List active Peninsula Equine services \u2014 slug, title, short description, starting price and category.",
  inputSchema: {
    category: z2.string().optional().describe("Optional category filter."),
    limit: z2.number().int().min(1).max(50).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: ctx.isAuthenticated() ? { headers: { Authorization: `Bearer ${ctx.getToken()}` } } : void 0,
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let q = supabase.from("managed_services").select("slug,title,short_description,starting_price,category,summary").eq("active", true).eq("is_demo", false).order("sort_order", { ascending: true }).limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { services: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aizkqajrzkvwuobisnzr";
var mcp_default = defineMcp({
  name: "peninsula-equine-mcp",
  title: "Peninsula Equine",
  version: "0.1.0",
  instructions: "Tools for Peninsula Equine \u2014 a Mornington Peninsula equine facilities builder. Use `list_projects` to read the live build register and `list_services` to see current service offerings. All tools are read-only.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_services_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
